---
title: "Coastal Darkening in the 20th century"
author: "Camille Crapart"
date: "2023-06-06"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
library(raster)
library(sf)
library(dplyr)
library(ggplot2)
library(colorspace)
library(directlabels)
library(RColorBrewer)
library(ggpubr)

library(spdep)
library(spatialreg)
```

```{r function-plot}
plot.export <- function(df, main.title){
 g <- ggplot(df, aes(x=year, y = TOC, col = sea))+geom_point()+
  geom_line(aes(group = sea))+
  scale_color_manual(values = c("firebrick","mediumaquamarine", "lightpink2"))+
  labs(y = "Predicted TOC concentration, mg/L", title = main.title, col = "Sea")+
  theme_minimal()+theme(axis.text.x =element_text(angle = 45))
h <- ggplot(df, aes(x=year, y = yearlyTOC.Tg, col = sea))+geom_point()+
  geom_line(aes(group = sea))+
  scale_color_manual(values = c("firebrick","mediumaquamarine", "lightpink2"))+
  labs(y = "Yearly export of TOC, Tg", title = "", col = "Sea")+
  theme_minimal()+theme(axis.text.x =element_text(angle = 45))

ggpubr::ggarrange(g,h, common.legend = T, legend = "bottom") %>% print()
}

plot.historical <- function(df, main.title){

for(i in unique(df$gid)){
g <- ggplot(filter(df, gid == i))+
  geom_point(aes(x = Year, y = TOC, col = Name), size = 0.5)+
  #geom_line(aes(x = Year, y = TOC, col = Name, group = Name), lty = 2)+
  geom_point(aes(x = decade, y = TOC.obs), col = "mediumaquamarine")+
  geom_line(aes(x = decade, y = TOC.obs, group = gid), col = "mediumaquamarine", lty = 1)+
  geom_point(aes(x = as.numeric(year), y = TOC.fit), col = "firebrick")+
  geom_line(aes(x = as.numeric(year), y = TOC.fit, group = gid), col = "firebrick", lty = 1)+
  labs(x = "", y = "TOC, mg/L", col = "River", title = main.title)+
  scale_color_brewer(palette = "Dark2")+
  expand_limits(x = 2029)+
  #facet_grid(cols = vars(Name))+
  theme_minimal()+theme(legend.position = "none")
h <- ggplot()+geom_sf(data = filter(wr.sf.wgs84, gid == i))+geom_sf(data = filter(st_as_sf(df), gid == i), aes(color = Name))+
  borders(regions = "Sweden")+scale_color_brewer(palette = "Dark2")+labs(color = "River")+theme_void()+theme(legend.position = "bottom")
ggpubr::ggarrange(g,h, widths = c(2,1)) %>% print()
}
  
}
```

# Hindcast
## LM logTOC ~ forest + logRunoff + TSdep

```{r lm-log, eval = T}
fen <- readRDS("fen.rds")

lm.log <- lm(logTOC ~ forest + logRunoff + TSdep, data = fen)
print(summary(lm.log))

qplot(x = lm.log$fitted.values, y = fen$logTOC)+geom_abline(slope = 1, intercept = 0, lty = 2)
qplot(x = lm.log$fitted.values,y = lm.log$residuals)
hist(lm.log$residuals)

qplot(x = fen$longitude, y = fen$latitude, col = (10^lm.log$fitted.values))+geom_point()+
  scale_colour_continuous_divergingx(palette = "RdYlBu", aesthetics = c("col"), mid = 10, rev = T, limits = lims, na.value = "black")+
  labs(col = "TOC, mg")+
  theme_void()

saveRDS(lm.log,"lmlog.rds")

```
## Prediction by decade


```{r load-lm-model}
toc_model <- readRDS("lmlog.rds")
```

```{r predict-1899-lmlog, eval = F}
forest <- readRDS("forest.1899.rds") %>% filter(!is.na(forest))

sdep <- readRDS("sdep.df.1899.rds") %>% st_as_sf() %>% dplyr::select(c("gid","tsdep")) %>% st_drop_geometry()
runoff <- readRDS("runoff.1899.noresm.rds") %>% as.data.frame() %>% dplyr::select(c("gid","runoff")) %>% filter(!is.na(runoff))

wr.sf.1899 <- merge(wr.sf, forest, by = "gid") %>% merge(sdep, by = "gid") %>% merge(runoff, by = "gid")

wr.sf.1899$Runoff <- wr.sf.1899$runoff * 365 * 24 * 60 * 60 # kg/y
wr.sf.1899$logRunoff <- wr.sf.1899$Runoff  %>% log10() #log10
wr.sf.1899$TSdep <- wr.sf.1899$tsdep * (-1) * 365 * 24 * 60 * 60 * 1e6 # converts to mg/year
wr.sf.1899$logTSdep <- log10(wr.sf.1899$TSdep)

wr.sf.1899$logTOC.fit <- predict(toc_model, newdata = wr.sf.1899) # predicts TOC in ug/L
wr.sf.1899$TOC.fit <- 10^wr.sf.1899$logTOC.fit 
wr.sf.1899$TOC.export <- with(wr.sf.1899, TOC.fit* Runoff * area) # mg/L * kg/m2/y * m2 -> mg/year

saveRDS(wr.sf.1899, "wr.sf.1899.lmlog.rds")
```

```{r predict-1909-lmlog, eval = F}
forest <- readRDS("forest.1909.rds") %>% filter(!is.na(forest))

sdep <- readRDS("sdep.df.1909.rds") %>% st_as_sf() %>% dplyr::select(c("gid","tsdep")) %>% st_drop_geometry()
runoff <- readRDS("runoff.1909.noresm.rds") %>% as.data.frame() %>% dplyr::select(c("gid","runoff")) %>% filter(!is.na(runoff))

wr.sf.1909 <- merge(wr.sf, forest, by = "gid") %>% merge(sdep, by = "gid") %>% merge(runoff, by = "gid")

wr.sf.1909$Runoff <- wr.sf.1909$runoff * 365 * 24 * 60 * 60 
wr.sf.1909$logRunoff <- (wr.sf.1909$Runoff) %>% log10()
wr.sf.1909$TSdep <- wr.sf.1909$tsdep * (-1) * 365 * 24 * 60 * 60 * 1e6 # converts to mg/year
wr.sf.1909$logTSdep <- log10(wr.sf.1909$TSdep)

wr.sf.1909$logTOC.fit <- predict(toc_model, newdata = wr.sf.1909)
wr.sf.1909$TOC.fit <- 10^wr.sf.1909$logTOC.fit
wr.sf.1909$TOC.export <- with(wr.sf.1909, TOC.fit*Runoff * area) # mg/L * kg/m2/y * m2 -> mg/year

saveRDS(wr.sf.1909, "wr.sf.1909.lmlog.rds")
```

```{r predict-1919-lmlog, eval = F}
forest <- readRDS("forest.1919.rds") %>% filter(!is.na(forest))

sdep <- readRDS("sdep.df.1919.rds") %>% st_as_sf() %>% dplyr::select(c("gid","tsdep")) %>% st_drop_geometry()
runoff <- readRDS("runoff.1919.noresm.rds") %>% as.data.frame() %>% dplyr::select(c("gid","runoff")) %>% filter(!is.na(runoff))

wr.sf.1919 <- merge(wr.sf, forest, by = "gid") %>% merge(sdep, by = "gid") %>% merge(runoff, by = "gid")

wr.sf.1919$Runoff <- wr.sf.1919$runoff * 365 * 24 * 60 * 60 
wr.sf.1919$logRunoff <- (wr.sf.1919$Runoff) %>% log10() 
wr.sf.1919$TSdep <- wr.sf.1919$tsdep * (-1) * 365 * 24 * 60 * 60 * 1e6 # converts to mg/year
wr.sf.1919$logTSdep <- log10(wr.sf.1919$TSdep)

wr.sf.1919$logTOC.fit <- predict(toc_model, newdata = wr.sf.1919)
wr.sf.1919$TOC.fit <- 10^wr.sf.1919$logTOC.fit
wr.sf.1919$TOC.export <- with(wr.sf.1919, TOC.fit*Runoff  * area) # mg/L * kg/m2/y * m2 -> mg/year

saveRDS(wr.sf.1919, "wr.sf.1919.lmlog.rds")
```

```{r predict-1929-lmlog, eval = F}
forest <- readRDS("forest.1929.rds") %>% filter(!is.na(forest))

sdep <- readRDS("sdep.df.1929.rds") %>% st_as_sf() %>% dplyr::select(c("gid","tsdep")) %>% st_drop_geometry()
runoff <- readRDS("runoff.1929.noresm.rds") %>% as.data.frame() %>% dplyr::select(c("gid","runoff")) %>% filter(!is.na(runoff))

wr.sf.1929 <- merge(wr.sf, forest, by = "gid") %>% merge(sdep, by = "gid") %>% merge(runoff, by = "gid")

wr.sf.1929$Runoff <- wr.sf.1929$runoff * 365 * 24 * 60 * 60 
wr.sf.1929$logRunoff <- (wr.sf.1929$Runoff) %>% log10()
wr.sf.1929$TSdep <- wr.sf.1929$tsdep * (-1) * 365 * 24 * 60 * 60 * 1e6 # converts to mg/year
wr.sf.1929$logTSdep <- log10(wr.sf.1929$TSdep)

wr.sf.1929$logTOC.fit <- predict(toc_model, newdata = wr.sf.1929)
wr.sf.1929$TOC.fit <- 10^wr.sf.1929$logTOC.fit 
wr.sf.1929$TOC.export <- with(wr.sf.1929, TOC.fit*Runoff * area) # mg/L * kg/m2/s * m2 -> mg/year

saveRDS(wr.sf.1929, "wr.sf.1929.lmlog.rds")
```

```{r predict-1939-lmlog, eval = F}
forest <- readRDS("forest.1939.rds") %>% filter(!is.na(forest))

sdep <- readRDS("sdep.df.1939.rds") %>% st_as_sf() %>% dplyr::select(c("gid","tsdep")) %>% st_drop_geometry()
runoff <- readRDS("runoff.1939.noresm.rds") %>% as.data.frame() %>% dplyr::select(c("gid","runoff")) %>% filter(!is.na(runoff))

wr.sf.1939 <- merge(wr.sf, forest, by = "gid") %>% merge(sdep, by = "gid") %>% merge(runoff, by = "gid")

wr.sf.1939$Runoff <- wr.sf.1939$runoff * 365 * 24 * 60 * 60 
wr.sf.1939$logRunoff <- (wr.sf.1939$Runoff) %>% log10()
wr.sf.1939$TSdep <- wr.sf.1939$tsdep * (-1) * 365 * 24 * 60 * 60 * 1e6 # converts to mg/year
wr.sf.1939$logTSdep <- log10(wr.sf.1939$TSdep)

wr.sf.1939$logTOC.fit <- predict(toc_model, newdata = wr.sf.1939)
wr.sf.1939$TOC.fit <- 10^wr.sf.1939$logTOC.fit
wr.sf.1939$TOC.export <- with(wr.sf.1939, TOC.fit*Runoff * area) # mg/L * kg/m2/y * m2 -> mg/year

saveRDS(wr.sf.1939, "wr.sf.1939.lmlog.rds")
```

```{r predict-1949-lmlog, eval = F}
forest <- readRDS("forest.1949.rds") %>% filter(!is.na(forest))

sdep <- readRDS("sdep.df.1949.rds") %>% st_as_sf() %>% dplyr::select(c("gid","tsdep")) %>% st_drop_geometry()
runoff <- readRDS("runoff.1949.noresm.rds") %>% as.data.frame() %>% dplyr::select(c("gid","runoff")) %>% filter(!is.na(runoff))

wr.sf.1949 <- merge(wr.sf, forest, by = "gid") %>% merge(sdep, by = "gid") %>% merge(runoff, by = "gid")

wr.sf.1949$Runoff <- wr.sf.1949$runoff * 365 * 24 * 60 * 60 
wr.sf.1949$logRunoff <- (wr.sf.1949$Runoff) %>% log10()
wr.sf.1949$TSdep <- wr.sf.1949$tsdep * (-1) * 365 * 24 * 60 * 60 * 1e6 # converts to mg/year
wr.sf.1949$logTSdep <- log10(wr.sf.1949$TSdep)

wr.sf.1949$logTOC.fit <- predict(toc_model, newdata = wr.sf.1949)
wr.sf.1949$TOC.fit <- 10^wr.sf.1949$logTOC.fit
wr.sf.1949$TOC.export <- with(wr.sf.1949, TOC.fit*Runoff * area) # mg/L * kg/m2/y * m2 -> mg/year

saveRDS(wr.sf.1949, "wr.sf.1949.lmlog.rds")
```

```{r predict-1959-lmlog, eval = F}
forest <- readRDS("forest.1959.rds") %>% filter(!is.na(forest))

sdep <- readRDS("sdep.df.1959.rds") %>% st_as_sf() %>% dplyr::select(c("gid","tsdep")) %>% st_drop_geometry()
runoff <- readRDS("runoff.1959.noresm.rds") %>% as.data.frame() %>% dplyr::select(c("gid","runoff")) %>% filter(!is.na(runoff))

wr.sf.1959 <- merge(wr.sf, forest, by = "gid") %>% merge(sdep, by = "gid") %>% merge(runoff, by = "gid")
 
wr.sf.1959$Runoff <- wr.sf.1959$runoff * 365 * 24 * 60 * 60 
wr.sf.1959$logRunoff <- (wr.sf.1959$Runoff) %>% log10()
wr.sf.1959$TSdep <- wr.sf.1959$tsdep * (-1) * 365 * 24 * 60 * 60 * 1e6 # converts to mg/year
wr.sf.1959$logTSdep <- log10(wr.sf.1959$TSdep)

wr.sf.1959$logTOC.fit <- predict(toc_model, newdata = wr.sf.1959)
wr.sf.1959$TOC.fit <- 10^wr.sf.1959$logTOC.fit
wr.sf.1959$TOC.export <- with(wr.sf.1959, TOC.fit*Runoff * area) # mg/L * kg/m2/s * m2 -> mg/year

saveRDS(wr.sf.1959, "wr.sf.1959.lmlog.rds")
```

```{r predict-1969-lmlog, eval = F}
forest <- readRDS("forest.1969.rds") %>% filter(!is.na(forest))

sdep <- readRDS("sdep.df.1969.rds") %>% st_as_sf() %>% dplyr::select(c("gid","tsdep")) %>% st_drop_geometry()
runoff <- readRDS("runoff.1969.noresm.rds") %>% as.data.frame() %>% dplyr::select(c("gid","runoff")) %>% filter(!is.na(runoff))

wr.sf.1969 <- merge(wr.sf, forest, by = "gid") %>% merge(sdep, by = "gid") %>% merge(runoff, by = "gid")

wr.sf.1969$Runoff <- wr.sf.1969$runoff * 365 * 24 * 60 * 60 
wr.sf.1969$logRunoff <- (wr.sf.1969$Runoff) %>% log10()
wr.sf.1969$TSdep <- wr.sf.1969$tsdep * (-1) * 365 * 24 * 60 * 60 * 1e6 # converts to mg/year
wr.sf.1969$logTSdep <- log10(wr.sf.1969$TSdep)

wr.sf.1969$logTOC.fit <- predict(toc_model, newdata = wr.sf.1969)
wr.sf.1969$TOC.fit <- 10^wr.sf.1969$logTOC.fit
wr.sf.1969$TOC.export <- with(wr.sf.1969, TOC.fit*Runoff * area) # mg/L * kg/m2/s * m2 -> mg/year

saveRDS(wr.sf.1969, "wr.sf.1969.lmlog.rds")
```

```{r predict-1979-lmlog, eval = F}
forest <- readRDS("forest.1979.rds") %>% filter(!is.na(forest))

sdep <- readRDS("sdep.df.1979.rds") %>% st_as_sf() %>% dplyr::select(c("gid","tsdep")) %>% st_drop_geometry()
runoff <- readRDS("runoff.1979.noresm.rds") %>% as.data.frame() %>% dplyr::select(c("gid","runoff")) %>% filter(!is.na(runoff))

wr.sf.1979 <- merge(wr.sf, forest, by = "gid") %>% merge(sdep, by = "gid") %>% merge(runoff, by = "gid")

wr.sf.1979$Runoff <- wr.sf.1979$runoff * 365 * 24 * 60 * 60 
wr.sf.1979$logRunoff <- (wr.sf.1979$Runoff) %>% log10()
wr.sf.1979$TSdep <- wr.sf.1979$tsdep * (-1) * 365 * 24 * 60 * 60 * 1e6 # converts to mg/year
wr.sf.1979$logTSdep <- log10(wr.sf.1979$TSdep)

wr.sf.1979$logTOC.fit <- predict(toc_model, newdata = wr.sf.1979)
wr.sf.1979$TOC.fit <- 10^wr.sf.1979$logTOC.fit
wr.sf.1979$TOC.export <- with(wr.sf.1979, TOC.fit*Runoff * area) # mg/L * kg/m2/s * m2 -> mg/year

saveRDS(wr.sf.1979, "wr.sf.1979.lmlog.rds")
```

```{r predict-1989-lmlog, eval = F}
forest <- readRDS("forest.1989.rds") %>% filter(!is.na(forest))

sdep <- readRDS("sdep.df.1989.rds") %>% st_as_sf() %>% dplyr::select(c("gid","tsdep")) %>% st_drop_geometry()
runoff <- readRDS("runoff.1989.noresm.rds") %>% as.data.frame() %>% dplyr::select(c("gid","runoff")) %>% filter(!is.na(runoff))

wr.sf.1989 <- merge(wr.sf, forest, by = "gid") %>% merge(sdep, by = "gid") %>% merge(runoff, by = "gid")

wr.sf.1989$Runoff <- wr.sf.1989$runoff * 365 * 24 * 60 * 60 
wr.sf.1989$logRunoff <- (wr.sf.1989$Runoff)  %>% log10()
wr.sf.1989$TSdep <- wr.sf.1989$tsdep * (-1) * 365 * 24 * 60 * 60 * 1e6 # converts to mg/year
wr.sf.1989$logTSdep <- log10(wr.sf.1989$TSdep)

wr.sf.1989$logTOC.fit <- predict(toc_model, newdata = wr.sf.1989)
wr.sf.1989$TOC.fit <- 10^wr.sf.1989$logTOC.fit
wr.sf.1989$TOC.export <- with(wr.sf.1989, TOC.fit*Runoff  * area) # mg/L * kg/m2/y * m2 -> mg/year

saveRDS(wr.sf.1989, "wr.sf.1989.lmlog.rds")
```

```{r predict-1999-lmlog, eval = F}
forest <- readRDS("forest.1999.rds") %>% filter(!is.na(forest))

sdep <- readRDS("sdep.df.1999.rds") %>% st_as_sf() %>% dplyr::select(c("gid","tsdep")) %>% st_drop_geometry()
runoff <- readRDS("runoff.1999.noresm.rds") %>% as.data.frame() %>% dplyr::select(c("gid","runoff")) %>% filter(!is.na(runoff))

wr.sf.1999 <- merge(wr.sf, forest, by = "gid") %>% merge(sdep, by = "gid") %>% merge(runoff, by = "gid")

wr.sf.1999$Runoff <- wr.sf.1999$runoff * 365 * 24 * 60 * 60 
wr.sf.1999$logRunoff <- (wr.sf.1999$Runoff) %>% log10()
wr.sf.1999$TSdep <- wr.sf.1999$tsdep * (-1) * 365 * 24 * 60 * 60 * 1e6 # converts to mg/year
wr.sf.1999$logTSdep <- log10(wr.sf.1999$TSdep)

wr.sf.1999$logTOC.fit <- predict(toc_model, newdata = wr.sf.1999)
wr.sf.1999$TOC.fit <- 10^wr.sf.1999$logTOC.fit
wr.sf.1999$TOC.export <- with(wr.sf.1999, TOC.fit*Runoff  * area) # mg/L * kg/m2/y * m2 -> mg/year

saveRDS(wr.sf.1999, "wr.sf.1999.lmlog.rds")
```

```{r predict-1999-lmlog-emep, eval = F}
forest <- readRDS("forest.1999.rds") %>% filter(!is.na(forest))

sdep <- readRDS("sdep.1999.rds") %>% st_as_sf() %>% dplyr::select(c("gid","tsdep")) %>% st_drop_geometry()
runoff <- readRDS("runoff.1999.noresm.rds") %>% as.data.frame() %>% dplyr::select(c("gid","runoff")) %>% filter(!is.na(runoff))

wr.sf.1999 <- merge(wr.sf, forest, by = "gid") %>% merge(sdep, by = "gid") %>% merge(runoff, by = "gid")

wr.sf.1999$Runoff <- wr.sf.1999$runoff * 365 * 24 * 60 * 60
wr.sf.1999$logRunoff <- (wr.sf.1999$Runoff) %>% log10()
wr.sf.1999$TSdep <- wr.sf.1999$tsdep # already mg/m2/year
wr.sf.1999$logTSdep <- log10(wr.sf.1999$TSdep)

wr.sf.1999$logTOC.fit <- predict(toc_model, newdata = wr.sf.1999)
wr.sf.1999$TOC.fit <- 10^wr.sf.1999$logTOC.fit
wr.sf.1999$TOC.export <- with(wr.sf.1999, TOC.fit*Runoff  * area) # mg/L * kg/m2/y * m2 -> mg/year

saveRDS(wr.sf.1999, "wr.sf.1999.lmlog.emep.rds")
```

```{r predict-2009-lm-emep, eval = F}
forest <- readRDS("forest.2009.rds") %>% filter(!is.na(forest))

sdep <- readRDS("sdep.2009.rds") %>% st_as_sf() %>% dplyr::select(c("gid","tsdep")) %>% st_drop_geometry()
runoff <- readRDS("runoff.2009.noresm.rds") %>% as.data.frame() %>% dplyr::select(c("gid","runoff")) %>% filter(!is.na(runoff))

wr.sf.2009 <- merge(wr.sf, forest, by = "gid") %>% merge(sdep, by = "gid") %>% merge(runoff, by = "gid")

wr.sf.2009$Runoff <- wr.sf.2009$runoff * 365 * 24 * 60 * 60
wr.sf.2009$logRunoff <- (wr.sf.2009$Runoff) %>% log10()
wr.sf.2009$TSdep <-  wr.sf.2009$tsdep
wr.sf.2009$logTSdep <- log10(wr.sf.2009$TSdep)

wr.sf.2009$logTOC.fit <- predict(toc_model, newdata = wr.sf.2009)
wr.sf.2009$TOC.fit <- 10^wr.sf.2009$logTOC.fit
wr.sf.2009$TOC.export <- with(wr.sf.2009, TOC.fit*Runoff  * area) # mg/L * kg/m2/y * m2 -> mg/year

saveRDS(wr.sf.2009, "wr.sf.2009.lmlog.rds")
```

```{r predict-2019-lm-emep, eval = F}
forest <- readRDS("forest.2019.rds") %>% filter(!is.na(forest))

sdep <- readRDS("sdep.2019.rds") %>% st_as_sf() %>% dplyr::select(c("gid","tsdep")) %>% st_drop_geometry()
runoff <- readRDS("runoff.2019.noresm.rds") %>% as.data.frame() %>% dplyr::select(c("gid","runoff")) %>% filter(!is.na(runoff)) %>% filter(runoff > 0)

wr.sf.2019 <- merge(wr.sf, forest, by = "gid") %>% merge(sdep, by = "gid") %>% merge(runoff, by = "gid")

wr.sf.2019$Runoff <- wr.sf.2019$runoff * 365 * 24 * 60 * 60
wr.sf.2019$logRunoff <- (wr.sf.2019$Runoff) %>% log10()
wr.sf.2019$TSdep <- wr.sf.2019$tsdep
wr.sf.2019$logTSdep <- log10(wr.sf.2019$TSdep)

wr.sf.2019$logTOC.fit <- predict(toc_model, newdata = wr.sf.2019)
wr.sf.2019$TOC.fit <- 10^wr.sf.2019$logTOC.fit
wr.sf.2019$TOC.export <- with(wr.sf.2019, TOC.fit*Runoff  * area) # mg/L * kg/m2/y * m2 -> mg/year

saveRDS(wr.sf.2019, "wr.sf.2019.lmlog.rds")
```

## Compare exports

```{r common-lmlog, eval = F}
selected.vars <- c("gid","TOC.fit","TOC.export","forest","Runoff","TSdep","geometry")

wr.sf.1899 <- readRDS("wr.sf.1899..lmlog.rds") %>% select(selected.vars)
wr.sf.1899$year <- "1899"

wr.sf.1909 <- readRDS("wr.sf.1909..lmlog.rds") %>% select(selected.vars)
wr.sf.1909$year <- "1909"

wr.sf.1919 <- readRDS("wr.sf.1919..lmlog.rds") %>% select(selected.vars)
wr.sf.1919$year <- "1919"

wr.sf.1929 <- readRDS("wr.sf.1929..lmlog.rds") %>% select(selected.vars)
wr.sf.1929$year <- "1929"

wr.sf.1939 <- readRDS("wr.sf.1939..lmlog.rds") %>% select(selected.vars)
wr.sf.1939$year <- "1939"

wr.sf.1949 <- readRDS("wr.sf.1949..lmlog.rds") %>% select(selected.vars)
wr.sf.1949$year <- "1949"

wr.sf.1959 <- readRDS("wr.sf.1959..lmlog.rds") %>% select(selected.vars)
wr.sf.1959$year <- "1959"

wr.sf.1969 <- readRDS("wr.sf.1969..lmlog.rds") %>% select(selected.vars)
wr.sf.1969$year <- "1969"

wr.sf.1979 <- readRDS("wr.sf.1979..lmlog.rds") %>% select(selected.vars)
wr.sf.1979$year <- "1979"

wr.sf.1989 <- readRDS("wr.sf.1989..lmlog.rds") %>% select(selected.vars)
wr.sf.1989$year <- "1989"

wr.sf.1999 <- readRDS("wr.sf.1999..lmlog.emep.rds") %>% select(selected.vars)
wr.sf.1999$year <- "1999"

wr.sf.2009 <- readRDS("wr.sf.2009..lmlog.rds") %>% select(selected.vars)
wr.sf.2009$year <- "2009"

wr.sf.2019 <- readRDS("wr.sf.2019..lmlog.rds") %>% select(selected.vars)
wr.sf.2019$year <- "2019"

wr.sf.past <- rbind(wr.sf.1899, wr.sf.1909) %>% rbind(wr.sf.1919) %>% 
              rbind(wr.sf.1929) %>% rbind(wr.sf.1939) %>% rbind(wr.sf.1949) %>% 
              rbind(wr.sf.1959) %>% rbind(wr.sf.1969) %>% rbind(wr.sf.1979) %>% 
              rbind(wr.sf.1989) %>% rbind(wr.sf.1999) %>% rbind(wr.sf.2009) %>%
              rbind(wr.sf.2019)

#wr.sf.past.mercator <- st_transform(wr.sf.past, st_crs(4326))
wr.sf.exp <- merge(wr.sf.past, st_drop_geometry(wr.basins), by = "gid")
wr.exp <- wr.sf.exp %>% st_drop_geometry()

saveRDS(wr.sf.exp, "wr.sf.exp..lmlog.rds")
saveRDS(wr.exp, "wr.exp..lmlog.rds")
```

```{r plot-exp-selm-itr}
wr.exp <- readRDS("wr.exp.selm.itr.rds")

basins.exp <- wr.exp  %>% filter(Runoff > 0 & !is.na(sea)) %>% group_by(sea,year) %>% summarise(TOCyearly = sum(TOC.export), TOC = mean(TOC.fit), forest = mean(forest), TSdep = mean(TSdep), Runoff = mean(Runoff))
basins.exp$yearlyTOC.Tg <- basins.exp$TOCyearly * 1e-15 # from mg to Tg

plot.export(basins.exp, "SELM logTOC~forest*logRunoff*TSdep")
```

## Comparison with historical data


```{r compare-swedish-lmlog}
merged.rivers <- readRDS("merged.rivers.rds")

wr.exp <- readRDS("wr.exp.lmlog.rds")

match.exp <- wr.exp %>% filter(gid %in% merged.rivers$gid) %>% merge(select(merged.rivers, c("Name","Year","decade","TOC","TOC.decade","gid")), by = "gid") 

obs.TOC.decade <- match.exp %>% group_by(gid,decade) %>% summarise(TOC.obs = mean(TOC))

total <- merge(match.exp, obs.TOC.decade, by = c("gid","decade"))

plot.historical(total, "SELM logTOC~forest*logRunoff*TSdep")

```

# Maps

```{r map-toc-1899, eval = F}
wr.sf.1899 <- readRDS("wr.sf.1899")

map.toc.1899 <- ggplot(wr.sf.1899)+geom_sf(aes(fill = TOC.fit, col = TOC.fit))+
   scale_colour_continuous_divergingx(palette = "RdYlBu", aesthetics = c("col","fill"), mid = 10, rev = T, limits = lims, na.value = "black")+
  labs(col = "TOC concentration\nin mg/L in 1899", fill = "TOC concentration\nin mg/L in 1899")+
  theme_void()

ggsave("map.toc.1899.png", map.toc.1899)
```

```{r map-toc-1909, eval = F}
wr.sf.1909 <- readRDS("wr.sf.1909")

map.toc.1909 <- ggplot(wr.sf.1909)+geom_sf(aes(fill = TOC.fit, col = TOC.fit))+
   scale_colour_continuous_divergingx(palette = "RdYlBu", aesthetics = c("col","fill"), mid = 10, rev = T, limits = lims, na.value = "black")+
  labs(col = "TOC concentration\nin mg/L in 1909", fill = "TOC concentration\nin mg/L in 1909")+
  theme_void()

ggsave("map.toc.1909.png", map.toc.1909)
```

```{r map-toc-1919, eval = F}
wr.sf.1919 <- readRDS("wr.sf.1919")

map.toc.1919 <- ggplot(wr.sf.1919)+geom_sf(aes(fill = TOC.fit, col = TOC.fit))+
   scale_colour_continuous_divergingx(palette = "RdYlBu", aesthetics = c("col","fill"), mid = 10, rev = T, limits = lims, na.value = "black")+
  labs(col = "TOC concentration\nin mg/L in 1919", fill = "TOC concentration\nin mg/L in 1919")+
  theme_void()

ggsave("map.toc.1919.png", map.toc.1919)
```

```{r map-toc-1929, eval = F}
wr.sf.1929 <- readRDS("wr.sf.1929")

map.toc.1929 <- ggplot(wr.sf.1929)+geom_sf(aes(fill = TOC.fit, col = TOC.fit))+
   scale_colour_continuous_divergingx(palette = "RdYlBu", aesthetics = c("col","fill"), mid = 10, rev = T, limits = lims, na.value = "black")+
  labs(col = "TOC concentration\nin mg/L in 1929", fill = "TOC concentration\nin mg/L in 1929")+
  theme_void()

ggsave("map.toc.1929.png", map.toc.1929)
```

```{r map-toc-1939, eval = F}
wr.sf.1939 <- readRDS("wr.sf.1939")

map.toc.1939 <- ggplot(wr.sf.1939)+geom_sf(aes(fill = TOC.fit, col = TOC.fit))+
   scale_colour_continuous_divergingx(palette = "RdYlBu", aesthetics = c("col","fill"), mid = 10, rev = T, limits = lims, na.value = "black")+
  labs(col = "TOC concentration\nin mg/L in 1939", fill = "TOC concentration\nin mg/L in 1939")+
  theme_void()

ggsave("map.toc.1939.png", map.toc.1939)
```


```{r map-toc-1949, eval = F}
wr.sf.1949 <- readRDS("wr.sf.1949")

map.toc.1949 <- ggplot(wr.sf.1949)+geom_sf(aes(fill = TOC.fit, col = TOC.fit))+
   scale_colour_continuous_divergingx(palette = "RdYlBu", aesthetics = c("col","fill"), mid = 10, rev = T, limits = lims, na.value = "black")+
  labs(col = "TOC concentration\nin mg/L in 1949", fill = "TOC concentration\nin mg/L in 1949")+
  theme_void()

ggsave("map.toc.1949.png", map.toc.1949)
```

```{r map-toc-1959, eval = F}
wr.sf.1959 <- readRDS("wr.sf.1959")

map.toc.1959 <- ggplot(wr.sf.1959)+geom_sf(aes(fill = TOC.fit, col = TOC.fit))+
   scale_colour_continuous_divergingx(palette = "RdYlBu", aesthetics = c("col","fill"), mid = 10, rev = T, limits = lims, na.value = "black")+
  labs(col = "TOC concentration\nin mg/L in 1959", fill = "TOC concentration\nin mg/L in 1959")+
  theme_void()

ggsave("map.toc.1959.png", map.toc.1959)
```



```{r map-toc-1969, eval = F}
wr.sf.1969 <- readRDS("wr.sf.1969")

map.toc.1969 <- ggplot(wr.sf.1969)+geom_sf(aes(fill = TOC.fit, col = TOC.fit))+
   scale_colour_continuous_divergingx(palette = "RdYlBu", aesthetics = c("col","fill"), mid = 10, rev = T, limits = lims, na.value = "black")+
  labs(col = "TOC concentration\nin mg/L in 1969", fill = "TOC concentration\nin mg/L in 1969")+
  theme_void()

ggsave("map.toc.1969.png", map.toc.1969)
```

```{r map-toc-1979, eval = F}
wr.sf.1979 <- readRDS("wr.sf.1979")

map.toc.1979 <- ggplot(wr.sf.1979)+geom_sf(aes(fill = TOC.fit, col = TOC.fit))+
   scale_colour_continuous_divergingx(palette = "RdYlBu", aesthetics = c("col","fill"), mid = 10, rev = T, limits = lims, na.value = "black")+
  labs(col = "TOC concentration\nin mg/L in 1979", fill = "TOC concentration\nin mg/L in 1979")+
  theme_void()

ggsave("map.toc.1979.png", map.toc.1979)
```

```{r map-toc-1989, eval = F}
wr.sf.1989 <- readRDS("wr.sf.1989")

map.toc.1989 <- ggplot(wr.sf.1989)+geom_sf(aes(fill = TOC.fit, col = TOC.fit))+
   scale_colour_continuous_divergingx(palette = "RdYlBu", aesthetics = c("col","fill"), mid = 10, rev = T, limits = lims, na.value = "black")+
  labs(col = "TOC concentration\nin mg/L in 1989", fill = "TOC concentration\nin mg/L in 1989")+
  theme_void()

ggsave("map.toc.1989.png", map.toc.1989)
```

```{r map-toc-1999, eval = F}
wr.sf.1999 <- readRDS("wr.sf.1999")

map.toc.1999 <- ggplot(wr.sf.1999)+geom_sf(aes(fill = TOC.fit, col = TOC.fit))+
   scale_colour_continuous_divergingx(palette = "RdYlBu", aesthetics = c("col","fill"), mid = 10, rev = T, limits = lims, na.value = "black")+
  labs(col = "TOC concentration\nin mg/L in 1999", fill = "TOC concentration\nin mg/L in 1999")+
  theme_void()

ggsave("map.toc.1999.png", map.toc.1999)
```

```{r map-toc-2009, eval = F}
wr.sf.2009 <- readRDS("wr.sf.2009")

map.toc.2009 <- ggplot(wr.sf.2009)+geom_sf(aes(fill = TOC.fit, col = TOC.fit))+
   scale_colour_continuous_divergingx(palette = "RdYlBu", aesthetics = c("col","fill"), mid = 10, rev = T, limits = lims, na.value = "black")+
  labs(col = "TOC concentration\nin mg/L in 1999", fill = "TOC concentration\nin mg/L in 1999")+
  theme_void()

ggsave("map.toc.2009.png", map.toc.2009)
```

```{r map-toc-2019, eval = F}
wr.sf.2019 <- readRDS("wr.sf.2019")

map.toc.2019 <- ggplot(wr.sf.2019)+geom_sf(aes(fill = TOC.fit, col = TOC.fit))+
   scale_colour_continuous_divergingx(palette = "RdYlBu", aesthetics = c("col","fill"), mid = 10, rev = T, limits = lims, na.value = "black")+
  labs(col = "TOC concentration\nin mg/L in 1999", fill = "TOC concentration\nin mg/L in 1999")+
  theme_void()

ggsave("map.toc.2019.png", map.toc.2019)
```